<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Savvy" failures="1" tests="9" name="Test" time="88.927" errors="0" timestamp="2025-01-26T22:40:34 IST">
  <testcase classname="testCases.TC_001_AccountRegistrationTest" name="verify_account_registration" time="8.826"/>
  <testcase classname="testCases.TC_002_LoginTest" name="verify_login" time="2.49"/>
  <testcase classname="testCases.TC_002_LoginTest" name="verify_login2" time="11.643">
    <failure type="java.lang.AssertionError" message="Login failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
at testCases.TC_002_LoginTest.verify_login2(TC_002_LoginTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_login2 -->
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="2.495"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="2.019"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="2.14"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="11.758"/>
  <testcase classname="testCases.TC_003_LoginDDT" name="verify_loginDDT" time="3.865"/>
  <testcase classname="testCases.TC_001_AccountRegistration_BulkTest" name="verify_account_registration" time="25.031"/>
</testsuite> <!-- Test -->
